name: GitHub metrics
on:
  schedule:
    - cron: "0 0-23/4 * * *"
  push:
    branches: 
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

        - name: Personal metrics
          if: ${{ success() || failure() }}
          uses: les4ne/metrics@master
          with:
            filename: metrics.svg
            token: ${{ secrets.METRICS_TOKEN }}
            committer_token: ${{ secrets.GITHUB_TOKEN }}
            base: "header, repositories"
            plugin_lines: yes
            plugin_isocalendar: yes
            config_timezone: Europe/Moscow
            config_order: base.header, isocalendar, base.repositories
            config_padding: 10%

        - name: Personal metrics (additional)
          if: ${{ success() || failure() }}
          uses: les4ne/metrics@master
          with:
            filename: metrics.additional.svg
            token: ${{ secrets.METRICS_TOKEN }}
            committer_token: ${{ secrets.GITHUB_TOKEN }}
            base: ""
            plugin_habits: yes
            plugin_habits_from: 200
            plugin_habits_facts: no
            plugin_habits_charts: yes
            plugin_languages: yes
            plugin_languages_ignored: tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
            plugin_languages_skipped: les4ne
            plugin_stars: yes
            plugin_stars_limit: 3
            config_timezone: Europe/Moscow
            config_order: languages, habits, stars
            config_padding: 6%, 10%

        - name: Topics plugin (mastered)
          if: ${{ success() || failure() }}
          uses: les4ne/metrics@master
          with:
            filename: metrics.plugin.topics.mastered.svg
            token: ${{ secrets.METRICS_TOKEN }}
            committer_token: ${{ secrets.GITHUB_TOKEN }}
            base: ""
            plugin_skyline: no
            plugin_topics: yes
            plugin_topics_mode: mastered
            plugins_errors_fatal: yes
            config_timezone: Europe/Moscow
            use_prebuilt_image: master

#         - name: PageSpeed plugin (detailed)
#           uses: pwndex/metrics@master
#           with:
#             filename: metrics.plugin.pagespeed.detailed.svg
#             token: ${{ secrets.METRICS_TOKEN }}
#             committer_token: ${{ secrets.GITHUB_TOKEN }}
#             base: ""
#             plugin_skyline: no
#             plugin_pagespeed: yes
#             plugin_pagespeed_detailed: yes
#             plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
#             plugins_errors_fatal: yes
#             config_timezone: Europe/Moscow
#             use_prebuilt_image: master

        - name: Activity plugin
          if: ${{ success() || failure() }}
          uses: les4ne/metrics@master
          with:
            filename: metrics.plugin.activity.svg
            token: ${{ secrets.METRICS_TOKEN }}
            committer_token: ${{ secrets.GITHUB_TOKEN }}
            base: ""
            plugin_skyline: no
            plugin_activity: yes
            plugin_activity_limit: 6
            plugin_activity_days: 0
            plugin_activity_filter: push, issue, pr, release
            plugins_errors_fatal: yes
            config_timezone: Europe/Moscow
            config_padding: 10%
            use_prebuilt_image: master

        - name: Achivements plugin
          if: ${{ success() || failure() }}
          uses: les4ne/metrics@master
          with:
            filename: metrics.plugin.achivements.svg
            token: ${{ secrets.METRICS_TOKEN }}
            committer_token: ${{ secrets.GITHUB_TOKEN }}
            plugin_achievements: yes
            plugin_achievements_threshold: C
            plugin_achievements_secrets: yes
            plugin_achievements_ignored: octonaut
            plugin_achievements_limit: 0
            config_timezone: Europe/Moscow
            use_prebuilt_image: master

        - name: Follow-up plugin
          if: ${{ success() || failure() }}
          uses: les4ne/metrics@master
          with:
            filename: metrics.plugin.followup.svg
            token: ${{ secrets.METRICS_TOKEN }}
            committer_token: ${{ secrets.GITHUB_TOKEN }}
            base: ""
            plugin_skyline: no
            plugin_followup: yes
            plugins_errors_fatal: yes
            config_timezone: Europe/Moscow
            use_prebuilt_image: master

        - name: Stargazers plugin
          if: ${{ success() || failure() }}
          uses: les4ne/metrics@master
          with:
            filename: metrics.plugin.stargazers.svg
            token: ${{ secrets.METRICS_TOKEN }}
            committer_token: ${{ secrets.GITHUB_TOKEN }}
            base: ""
            plugin_skyline: no
            plugin_stargazers: yes
            plugins_errors_fatal: yes
            config_timezone: Europe/Moscow
            use_prebuilt_image: master
